# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-tecnico-richardhg
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:537124953041:table/SwarsTable


functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  
  list:
    handler: src/listar.getAll
    events:
      - httpApi:
          path: /api/sw
          method: get
  view:
    handler: src/ver.getOne
    events:
      - httpApi:
          path: /api/sw/{id}
          method: get
  create:
    handler: src/registrar.create
    events:
      - httpApi:
          path: /api/sw
          method: post
  edit:
    handler: src/editar.update
    events:
      - httpApi:
          path: /api/sw/{id}
          method: put
  delete:
    handler: src/eliminar.remove
    events:
      - httpApi:
          path: /api/sw/{id}
          method: delete
  verExternal:
    handler: src/verExterno.getOneExternal
    events:
      - httpApi:
          path: /api/external/sw/{id}
          method: get
  
resources:
  Resources:
    SwarsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SwarsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
